name: 01 Baiscs First WorkFlow


on:
  workflow_dispatch

jobs:
  print-hello-world:
    runs-on: ubuntu-latest
    steps:
      - name: Print Hello World
        run: echo "Hello World from step 1"

      - name: Step 2
        run: echo "Hello World from step 2"


  print-hello-world-job-two:
    runs-on: ubuntu-latest
    steps:
      - name: Print Hello World from job Two
        run: echo "Hello World from job Two from step 1"

      - name: Step 2
        run: echo "Hello World from job Two from step 2"
