name: 03 Baiscs Events


on: 
  # pull_request:
  #     types: [closed, reopened]
      # types:
      #   - closed
      #   - reopened



jobs:
  print-hello-world:
    runs-on: ubuntu-latest
    steps:
      - name: Print Hello World
        run: echo "Hello World from step 1"

      - name: Step 2
        run: echo "Hello World from step 2"

